-- 코드를 입력하세요
WITH HOUR_TABLE AS (
    SELECT '0' AS HOUR
    UNION ALL
    SELECT '1' AS HOUR
    UNION ALL
    SELECT '2' AS HOUR
    UNION ALL
    SELECT '3' AS HOUR
    UNION ALL
    SELECT '4' AS HOUR
    UNION ALL
    SELECT '5' AS HOUR
    UNION ALL
    SELECT '6' AS HOUR
    UNION ALL
    SELECT '7' AS HOUR
    UNION ALL
    SELECT '8' AS HOUR
    UNION ALL
    SELECT '9' AS HOUR
    UNION ALL
    SELECT '10' AS HOUR
    UNION ALL
    SELECT '11' AS HOUR
    UNION ALL
    SELECT '12' AS HOUR
    UNION ALL
    SELECT '13' AS HOUR
    UNION ALL
    SELECT '14' AS HOUR
    UNION ALL
    SELECT '15' AS HOUR
    UNION ALL
    SELECT '16' AS HOUR
    UNION ALL
    SELECT '17' AS HOUR
    UNION ALL
    SELECT '18' AS HOUR
    UNION ALL
    SELECT '19' AS HOUR
    UNION ALL
    SELECT '20' AS HOUR
    UNION ALL
    SELECT '21' AS HOUR
    UNION ALL
    SELECT '22' AS HOUR
    UNION ALL
    SELECT '23' AS HOUR
) 

SELECT 
    ht.HOUR,
    COUNT(ao.DATETIME) AS COUNT
FROM HOUR_TABLE AS ht
LEFT JOIN ANIMAL_OUTS AS ao ON ht.HOUR = HOUR(ao.DATETIME)
GROUP BY ht.HOUR

---
-- 다른사람 풀이 변수할당하여, 변수와 수가 동일한 경우를 카운트.(변수선언은 생각도못했네..)
-- SET @HOUR = -1;
-- SELECT (@HOUR := @HOUR +1) AS HOUR,
--     (SELECT COUNT(HOUR(DATETIME)) 
--     FROM ANIMAL_OUTS 
--     WHERE HOUR(DATETIME)=@HOUR) AS COUNT 
--     FROM ANIMAL_OUTS
-- WHERE @HOUR < 23;
