-- 코드를 작성해주세요
SELECT
    hd.DEPT_ID,
    hd.DEPT_NAME_EN,
    ROUND(avg(he.SAL)) AS AVG_SAL
FROM HR_EMPLOYEES he
LEFT JOIN HR_DEPARTMENT hd ON he.DEPT_ID = hd.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC